version: '3.5'

# SERVICES
services:
  #CALL DOCKERFILE
  poll:
    build: ./poll
    container_name: poll
    ports:
      - "5000:80"
    restart: always
    environment:
      - REDIS=redis
    networks: 
      - poll-tier

  result:
    build: ./result
    container_name: result
    ports:
      - "5001:80"
    restart: always
    environment:
      - DB=postgres://postgres:password@db/postgres
    networks: 
      - result-tier

  worker:
    build: ./worker
    container_name: worker
    restart: always
    environment:
      - REDIS=redis
      - DB=db
    networks: 
      - back-tier

  #DATABASE
  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    restart: always
    networks: 
      - poll-tier
      - back-tier

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRESS_USER=postgress
      - POSTGRESS_PASSWORD=password
      - POSTGRESS_DB=postgress
    networks: 
      - result-tier
      - back-tier
    volumes:
      - ./db-data:/var/lib/postgresql/data

#NETWORK
networks:
  poll-tier:
    name: poll-tier
  result-tier:
    name: result-tier
  back-tier:
    name: back-tier

#VOLUMES
volumes:
  db-data:
    name: db-data